platform :ios, '9.0'
swift_version='4.0'
inhibit_all_warnings!
use_frameworks!

target 'tryon-module-ios_Example' do
  pod 'tryon-module-ios-debug', :path => '../'

  pod 'SEPFoundation', :path => '../../SEPFoundation'
  pod 'FMTFoundation', :path => '../../FMTFoundation'

  target 'tryon-module-ios_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
