platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

target 'TestProject' do

    pod 'tryon-module-ios-debug', :path => '../tryon-module', :configuration => ['Debug']
    pod 'tryon-module-ios', :path => '../tryon-module', :configuration => ['Release']

end
